import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "./components/ui/sonner";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { cn } from "./lib/utils";
import EdgeAccents from "./components/EdgeAccents";
import { Suspense } from "react";
import Loading from "./components/Loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen",
          geistSans.variable,
          geistMono.variable,
          "antialiased bg-sb-background text-sb-foreground"
        )}
      >
        <Suspense fallback={<Loading />}>
          <Header />
          <EdgeAccents />
          <main className="relative flex-grow px-4 md:px-10 mx-auto w-full max-w-7xl my-10 md:my-20">
            <div className="relative z-10">{children}</div>
          </main>

          <Footer />
        </Suspense>
        <Toaster />
      </body>
    </html>
  );
}
